# Generated by Django 5.1.4 on 2025-01-30 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('desc', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='image/')),
                ('author', models.CharField(max_length=20)),
            ],
        ),
    ]
