# Generated by Django 5.1.4 on 2025-01-31 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_comments_postcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postcategory',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blogpost.postcategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='cow.jpg', upload_to='image/'),
        ),
    ]
