# Generated by Django 5.1.4 on 2025-01-31 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0004_remove_postcategory_post_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='category',
            field=models.CharField(default='General', max_length=50),
        ),
    ]
