# Generated by Django 5.1.4 on 2025-02-01 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0005_alter_postcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='author',
            field=models.TextField(max_length=100),
        ),
    ]
