# Generated by Django 5.1.4 on 2025-02-10 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0007_alter_comments_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.date(2025, 2, 10), null=True),
        ),
    ]
