# Generated by Django 5.1.4 on 2025-02-11 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0011_comments_reply_author_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 11, 2, 7, 19, 117290), null=True),
        ),
    ]
