# Generated by Django 5.1.4 on 2025-02-11 19:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0013_alter_post_time_post_like_dislike_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='total_likes_dislike',
            old_name='diskes',
            new_name='dislikes',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 11, 19, 49, 23, 324195), null=True),
        ),
    ]
