# Generated by Django 5.1.4 on 2025-02-11 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0014_rename_diskes_total_likes_dislike_dislikes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 11, 19, 54, 16, 671265), null=True),
        ),
        migrations.AlterField(
            model_name='total_likes_dislike',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='total_likes_dislike',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
