# Generated by Django 5.1.4 on 2025-02-12 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0016_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_dislikes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='total_likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 0, 22, 38, 865073), null=True),
        ),
        migrations.DeleteModel(
            name='Total_Likes_Dislike',
        ),
    ]
