# Generated by Django 5.1.4 on 2025-02-12 00:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0017_post_total_dislikes_post_total_likes_alter_post_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 0, 23, 13, 219043), null=True),
        ),
    ]
