# Generated by Django 5.1.4 on 2025-02-12 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0020_author_total_followers_author_total_follows_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 18, 35, 42, 553988), null=True),
        ),
    ]
