# Generated by Django 5.1.4 on 2025-02-12 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0021_follow_status_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='category',
            field=models.CharField(choices=[('reader', 'reader'), ('author', 'author')], default='reader', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 12, 22, 37, 45, 25181), null=True),
        ),
    ]
