# Generated by Django 5.1.4 on 2025-02-13 00:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0022_author_category_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='total_posts',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 13, 0, 42, 13, 294929), null=True),
        ),
    ]
