# Generated by Django 5.1.4 on 2025-02-13 01:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0023_author_total_posts_alter_post_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='email',
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 13, 1, 10, 24, 909282), null=True),
        ),
    ]
