# Generated by Django 5.1.4 on 2025-02-13 01:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0024_remove_author_email_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='category',
            field=models.CharField(default='reader', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 13, 1, 11, 58, 678883), null=True),
        ),
    ]
