# Generated by Django 5.1.4 on 2025-02-13 23:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0025_alter_author_category_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='intro',
            field=models.TextField(blank='True', default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 13, 23, 54, 20, 30419), null=True),
        ),
    ]
