# Generated by Django 5.1.4 on 2025-02-14 00:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0026_author_intro_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 14, 0, 3, 47, 648993), null=True),
        ),
    ]
