# Generated by Django 5.1.4 on 2025-02-14 00:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0027_alter_post_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.CharField(max_length=70)),
                ('company_intro', models.TextField(max_length=2000)),
                ('image', models.ImageField(blank=True, default='cow.jpg', null=True, upload_to='image/')),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 14, 0, 22, 44, 317040), null=True),
        ),
    ]
