# Generated by Django 5.1.4 on 2025-02-15 23:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0029_alter_post_time_postimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 15, 23, 12, 26, 978283), null=True),
        ),
    ]
