# Generated by Django 5.1.4 on 2025-02-15 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0030_alter_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 15, 23, 14, 1, 467833, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
