# Generated by Django 5.1.4 on 2025-02-15 23:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0031_alter_post_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='last_updated',
            field=models.TimeField(blank=True, null=True, verbose_name=datetime.datetime(2025, 2, 15, 23, 15, 39, 582899)),
        ),
        migrations.AlterField(
            model_name='post',
            name='time',
            field=models.DateField(blank=True, default=datetime.datetime(2025, 2, 15, 23, 15, 39, 582586, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
